[platformio]
default_envs = esp32dev

data_dir = .pio/data

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = time, colorize
lib_deps =
    sandeepmistry/LoRa @ ^0.8.0
build_flags =
    -I firmware/include
    -D SAHAYAK_PROTOCOL_VERSION=1
